/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReferenceIndexRouteImport } from './routes/reference.index'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as ReferenceChar123endpointSlugChar125DotmdRouteImport } from './routes/reference/{$endpointSlug}[.]md'
import { Route as ReferenceEndpointSlugRouteImport } from './routes/reference/$endpointSlug'
import { Route as GuidesChar123guideSlugChar125DotmdRouteImport } from './routes/guides/{$guideSlug}[.]md'
import { Route as GuidesGuideSlugRouteImport } from './routes/guides/$guideSlug'
import { Route as DocsGuideSlugRouteImport } from './routes/docs/$guideSlug'
import { Route as AuthTermsRouteImport } from './routes/auth/terms'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as ApiExecuteRouteImport } from './routes/api/execute'
import { Route as VVersionSlugOpenapiDotjsonRouteImport } from './routes/v/$versionSlug/openapi[.]json'
import { Route as VVersionSlugLlmsDottxtRouteImport } from './routes/v/$versionSlug/llms[.]txt'
import { Route as AppOrganizationSlugSettingsRouteImport } from './routes/app/$organizationSlug/settings'
import { Route as AppOrganizationSlugProjectsRouteImport } from './routes/app/$organizationSlug/projects'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSettingsRouteImport } from './routes/api/ai/settings'
import { Route as ApiAiPublicChatRouteImport } from './routes/api/ai/public-chat'
import { Route as ApiAiChatRouteImport } from './routes/api/ai/chat'
import { Route as VersionSlugReferenceEndpointSlugRouteImport } from './routes/$versionSlug/reference/$endpointSlug'
import { Route as VersionSlugDocsGuideSlugRouteImport } from './routes/$versionSlug/docs/$guideSlug'
import { Route as DocsOrganizationSlugProjectSlugIndexRouteImport } from './routes/docs/$organizationSlug/$projectSlug.index'
import { Route as VVersionSlugReferenceEndpointSlugRouteImport } from './routes/v/$versionSlug/reference/$endpointSlug'
import { Route as VVersionSlugGuidesGuideSlugRouteImport } from './routes/v/$versionSlug/guides/$guideSlug'
import { Route as DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRouteImport } from './routes/docs/$organizationSlug/$projectSlug/{$endpointSlug}[.]md'
import { Route as DocsOrganizationSlugProjectSlugOpenapiDotjsonRouteImport } from './routes/docs/$organizationSlug/$projectSlug/openapi[.]json'
import { Route as DocsOrganizationSlugProjectSlugLlmsDottxtRouteImport } from './routes/docs/$organizationSlug/$projectSlug/llms[.]txt'
import { Route as DocsOrganizationSlugProjectSlugEndpointSlugRouteImport } from './routes/docs/$organizationSlug/$projectSlug/$endpointSlug'
import { Route as AppOrganizationSlugProjectsProjectSlugIndexRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug.index'
import { Route as DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRouteImport } from './routes/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}[.]md'
import { Route as DocsOrganizationSlugProjectSlugGuidesGuideSlugRouteImport } from './routes/docs/$organizationSlug/$projectSlug/guides/$guideSlug'
import { Route as AppOrganizationSlugProjectsProjectSlugSettingsRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/settings'
import { Route as AppOrganizationSlugProjectsProjectSlugMetricsRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/metrics'
import { Route as AppOrganizationSlugProjectsProjectSlugAiRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/ai'
import { Route as AppOrganizationSlugProjectsProjectSlugGuidesIndexRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/guides.index'
import { Route as AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug'
import { Route as AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug'
import { Route as AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug.index'
import { Route as AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings'
import { Route as AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation'
import { Route as AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides.index'
import { Route as AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug'
import { Route as AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRouteImport } from './routes/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug'

const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceIndexRoute = ReferenceIndexRouteImport.update({
  id: '/reference/',
  path: '/reference/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenceChar123endpointSlugChar125DotmdRoute =
  ReferenceChar123endpointSlugChar125DotmdRouteImport.update({
    id: '/reference/{$endpointSlug}.md',
    path: '/reference/{$endpointSlug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenceEndpointSlugRoute = ReferenceEndpointSlugRouteImport.update({
  id: '/reference/$endpointSlug',
  path: '/reference/$endpointSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesChar123guideSlugChar125DotmdRoute =
  GuidesChar123guideSlugChar125DotmdRouteImport.update({
    id: '/guides/{$guideSlug}.md',
    path: '/guides/{$guideSlug}.md',
    getParentRoute: () => rootRouteImport,
  } as any)
const GuidesGuideSlugRoute = GuidesGuideSlugRouteImport.update({
  id: '/guides/$guideSlug',
  path: '/guides/$guideSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsGuideSlugRoute = DocsGuideSlugRouteImport.update({
  id: '/docs/$guideSlug',
  path: '/docs/$guideSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTermsRoute = AuthTermsRouteImport.update({
  id: '/auth/terms',
  path: '/auth/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExecuteRoute = ApiExecuteRouteImport.update({
  id: '/api/execute',
  path: '/api/execute',
  getParentRoute: () => rootRouteImport,
} as any)
const VVersionSlugOpenapiDotjsonRoute =
  VVersionSlugOpenapiDotjsonRouteImport.update({
    id: '/v/$versionSlug/openapi.json',
    path: '/v/$versionSlug/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const VVersionSlugLlmsDottxtRoute = VVersionSlugLlmsDottxtRouteImport.update({
  id: '/v/$versionSlug/llms.txt',
  path: '/v/$versionSlug/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationSlugSettingsRoute =
  AppOrganizationSlugSettingsRouteImport.update({
    id: '/app/$organizationSlug/settings',
    path: '/app/$organizationSlug/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationSlugProjectsRoute =
  AppOrganizationSlugProjectsRouteImport.update({
    id: '/app/$organizationSlug/projects',
    path: '/app/$organizationSlug/projects',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSettingsRoute = ApiAiSettingsRouteImport.update({
  id: '/api/ai/settings',
  path: '/api/ai/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPublicChatRoute = ApiAiPublicChatRouteImport.update({
  id: '/api/ai/public-chat',
  path: '/api/ai/public-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai/chat',
  path: '/api/ai/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const VersionSlugReferenceEndpointSlugRoute =
  VersionSlugReferenceEndpointSlugRouteImport.update({
    id: '/$versionSlug/reference/$endpointSlug',
    path: '/$versionSlug/reference/$endpointSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const VersionSlugDocsGuideSlugRoute =
  VersionSlugDocsGuideSlugRouteImport.update({
    id: '/$versionSlug/docs/$guideSlug',
    path: '/$versionSlug/docs/$guideSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsOrganizationSlugProjectSlugIndexRoute =
  DocsOrganizationSlugProjectSlugIndexRouteImport.update({
    id: '/docs/$organizationSlug/$projectSlug/',
    path: '/docs/$organizationSlug/$projectSlug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const VVersionSlugReferenceEndpointSlugRoute =
  VVersionSlugReferenceEndpointSlugRouteImport.update({
    id: '/v/$versionSlug/reference/$endpointSlug',
    path: '/v/$versionSlug/reference/$endpointSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const VVersionSlugGuidesGuideSlugRoute =
  VVersionSlugGuidesGuideSlugRouteImport.update({
    id: '/v/$versionSlug/guides/$guideSlug',
    path: '/v/$versionSlug/guides/$guideSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute =
  DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRouteImport.update(
    {
      id: '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md',
      path: '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute =
  DocsOrganizationSlugProjectSlugOpenapiDotjsonRouteImport.update({
    id: '/docs/$organizationSlug/$projectSlug/openapi.json',
    path: '/docs/$organizationSlug/$projectSlug/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsOrganizationSlugProjectSlugLlmsDottxtRoute =
  DocsOrganizationSlugProjectSlugLlmsDottxtRouteImport.update({
    id: '/docs/$organizationSlug/$projectSlug/llms.txt',
    path: '/docs/$organizationSlug/$projectSlug/llms.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const DocsOrganizationSlugProjectSlugEndpointSlugRoute =
  DocsOrganizationSlugProjectSlugEndpointSlugRouteImport.update({
    id: '/docs/$organizationSlug/$projectSlug/$endpointSlug',
    path: '/docs/$organizationSlug/$projectSlug/$endpointSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationSlugProjectsProjectSlugIndexRoute =
  AppOrganizationSlugProjectsProjectSlugIndexRouteImport.update({
    id: '/$projectSlug/',
    path: '/$projectSlug/',
    getParentRoute: () => AppOrganizationSlugProjectsRoute,
  } as any)
const DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute =
  DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRouteImport.update(
    {
      id: '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md',
      path: '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md',
      getParentRoute: () => rootRouteImport,
    } as any,
  )
const DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute =
  DocsOrganizationSlugProjectSlugGuidesGuideSlugRouteImport.update({
    id: '/docs/$organizationSlug/$projectSlug/guides/$guideSlug',
    path: '/docs/$organizationSlug/$projectSlug/guides/$guideSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrganizationSlugProjectsProjectSlugSettingsRoute =
  AppOrganizationSlugProjectsProjectSlugSettingsRouteImport.update({
    id: '/$projectSlug/settings',
    path: '/$projectSlug/settings',
    getParentRoute: () => AppOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationSlugProjectsProjectSlugMetricsRoute =
  AppOrganizationSlugProjectsProjectSlugMetricsRouteImport.update({
    id: '/$projectSlug/metrics',
    path: '/$projectSlug/metrics',
    getParentRoute: () => AppOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationSlugProjectsProjectSlugAiRoute =
  AppOrganizationSlugProjectsProjectSlugAiRouteImport.update({
    id: '/$projectSlug/ai',
    path: '/$projectSlug/ai',
    getParentRoute: () => AppOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute =
  AppOrganizationSlugProjectsProjectSlugGuidesIndexRouteImport.update({
    id: '/$projectSlug/guides/',
    path: '/$projectSlug/guides/',
    getParentRoute: () => AppOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute =
  AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRouteImport.update(
    {
      id: '/$projectSlug/reference/$endpointSlug',
      path: '/$projectSlug/reference/$endpointSlug',
      getParentRoute: () => AppOrganizationSlugProjectsRoute,
    } as any,
  )
const AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute =
  AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRouteImport.update({
    id: '/$projectSlug/guides/$guideSlug',
    path: '/$projectSlug/guides/$guideSlug',
    getParentRoute: () => AppOrganizationSlugProjectsRoute,
  } as any)
const AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute =
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRouteImport.update(
    {
      id: '/$projectSlug/versions/$versionSlug/',
      path: '/$projectSlug/versions/$versionSlug/',
      getParentRoute: () => AppOrganizationSlugProjectsRoute,
    } as any,
  )
const AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute =
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRouteImport.update(
    {
      id: '/$projectSlug/versions/$versionSlug/settings',
      path: '/$projectSlug/versions/$versionSlug/settings',
      getParentRoute: () => AppOrganizationSlugProjectsRoute,
    } as any,
  )
const AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute =
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRouteImport.update(
    {
      id: '/$projectSlug/versions/$versionSlug/navigation',
      path: '/$projectSlug/versions/$versionSlug/navigation',
      getParentRoute: () => AppOrganizationSlugProjectsRoute,
    } as any,
  )
const AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute =
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRouteImport.update(
    {
      id: '/$projectSlug/versions/$versionSlug/guides/',
      path: '/$projectSlug/versions/$versionSlug/guides/',
      getParentRoute: () => AppOrganizationSlugProjectsRoute,
    } as any,
  )
const AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute =
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRouteImport.update(
    {
      id: '/$projectSlug/versions/$versionSlug/reference/$endpointSlug',
      path: '/$projectSlug/versions/$versionSlug/reference/$endpointSlug',
      getParentRoute: () => AppOrganizationSlugProjectsRoute,
    } as any,
  )
const AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute =
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRouteImport.update(
    {
      id: '/$projectSlug/versions/$versionSlug/guides/$guideSlug',
      path: '/$projectSlug/versions/$versionSlug/guides/$guideSlug',
      getParentRoute: () => AppOrganizationSlugProjectsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/api/execute': typeof ApiExecuteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/terms': typeof AuthTermsRoute
  '/docs/$guideSlug': typeof DocsGuideSlugRoute
  '/guides/$guideSlug': typeof GuidesGuideSlugRoute
  '/guides/{$guideSlug}.md': typeof GuidesChar123guideSlugChar125DotmdRoute
  '/reference/$endpointSlug': typeof ReferenceEndpointSlugRoute
  '/reference/{$endpointSlug}.md': typeof ReferenceChar123endpointSlugChar125DotmdRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/$versionSlug/docs/$guideSlug': typeof VersionSlugDocsGuideSlugRoute
  '/$versionSlug/reference/$endpointSlug': typeof VersionSlugReferenceEndpointSlugRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/public-chat': typeof ApiAiPublicChatRoute
  '/api/ai/settings': typeof ApiAiSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationSlug/projects': typeof AppOrganizationSlugProjectsRouteWithChildren
  '/app/$organizationSlug/settings': typeof AppOrganizationSlugSettingsRoute
  '/v/$versionSlug/llms.txt': typeof VVersionSlugLlmsDottxtRoute
  '/v/$versionSlug/openapi.json': typeof VVersionSlugOpenapiDotjsonRoute
  '/docs/$organizationSlug/$projectSlug/$endpointSlug': typeof DocsOrganizationSlugProjectSlugEndpointSlugRoute
  '/docs/$organizationSlug/$projectSlug/llms.txt': typeof DocsOrganizationSlugProjectSlugLlmsDottxtRoute
  '/docs/$organizationSlug/$projectSlug/openapi.json': typeof DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute
  '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md': typeof DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute
  '/v/$versionSlug/guides/$guideSlug': typeof VVersionSlugGuidesGuideSlugRoute
  '/v/$versionSlug/reference/$endpointSlug': typeof VVersionSlugReferenceEndpointSlugRoute
  '/docs/$organizationSlug/$projectSlug/': typeof DocsOrganizationSlugProjectSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/ai': typeof AppOrganizationSlugProjectsProjectSlugAiRoute
  '/app/$organizationSlug/projects/$projectSlug/metrics': typeof AppOrganizationSlugProjectsProjectSlugMetricsRoute
  '/app/$organizationSlug/projects/$projectSlug/settings': typeof AppOrganizationSlugProjectsProjectSlugSettingsRoute
  '/docs/$organizationSlug/$projectSlug/guides/$guideSlug': typeof DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute
  '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md': typeof DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute
  '/app/$organizationSlug/projects/$projectSlug/': typeof AppOrganizationSlugProjectsProjectSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug': typeof AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug': typeof AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/guides/': typeof AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/api/execute': typeof ApiExecuteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/terms': typeof AuthTermsRoute
  '/docs/$guideSlug': typeof DocsGuideSlugRoute
  '/guides/$guideSlug': typeof GuidesGuideSlugRoute
  '/guides/{$guideSlug}.md': typeof GuidesChar123guideSlugChar125DotmdRoute
  '/reference/$endpointSlug': typeof ReferenceEndpointSlugRoute
  '/reference/{$endpointSlug}.md': typeof ReferenceChar123endpointSlugChar125DotmdRoute
  '/docs': typeof DocsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/reference': typeof ReferenceIndexRoute
  '/$versionSlug/docs/$guideSlug': typeof VersionSlugDocsGuideSlugRoute
  '/$versionSlug/reference/$endpointSlug': typeof VersionSlugReferenceEndpointSlugRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/public-chat': typeof ApiAiPublicChatRoute
  '/api/ai/settings': typeof ApiAiSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationSlug/projects': typeof AppOrganizationSlugProjectsRouteWithChildren
  '/app/$organizationSlug/settings': typeof AppOrganizationSlugSettingsRoute
  '/v/$versionSlug/llms.txt': typeof VVersionSlugLlmsDottxtRoute
  '/v/$versionSlug/openapi.json': typeof VVersionSlugOpenapiDotjsonRoute
  '/docs/$organizationSlug/$projectSlug/$endpointSlug': typeof DocsOrganizationSlugProjectSlugEndpointSlugRoute
  '/docs/$organizationSlug/$projectSlug/llms.txt': typeof DocsOrganizationSlugProjectSlugLlmsDottxtRoute
  '/docs/$organizationSlug/$projectSlug/openapi.json': typeof DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute
  '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md': typeof DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute
  '/v/$versionSlug/guides/$guideSlug': typeof VVersionSlugGuidesGuideSlugRoute
  '/v/$versionSlug/reference/$endpointSlug': typeof VVersionSlugReferenceEndpointSlugRoute
  '/docs/$organizationSlug/$projectSlug': typeof DocsOrganizationSlugProjectSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/ai': typeof AppOrganizationSlugProjectsProjectSlugAiRoute
  '/app/$organizationSlug/projects/$projectSlug/metrics': typeof AppOrganizationSlugProjectsProjectSlugMetricsRoute
  '/app/$organizationSlug/projects/$projectSlug/settings': typeof AppOrganizationSlugProjectsProjectSlugSettingsRoute
  '/docs/$organizationSlug/$projectSlug/guides/$guideSlug': typeof DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute
  '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md': typeof DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute
  '/app/$organizationSlug/projects/$projectSlug': typeof AppOrganizationSlugProjectsProjectSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug': typeof AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug': typeof AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/guides': typeof AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/onboarding': typeof OnboardingRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/api/execute': typeof ApiExecuteRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/terms': typeof AuthTermsRoute
  '/docs/$guideSlug': typeof DocsGuideSlugRoute
  '/guides/$guideSlug': typeof GuidesGuideSlugRoute
  '/guides/{$guideSlug}.md': typeof GuidesChar123guideSlugChar125DotmdRoute
  '/reference/$endpointSlug': typeof ReferenceEndpointSlugRoute
  '/reference/{$endpointSlug}.md': typeof ReferenceChar123endpointSlugChar125DotmdRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/reference/': typeof ReferenceIndexRoute
  '/$versionSlug/docs/$guideSlug': typeof VersionSlugDocsGuideSlugRoute
  '/$versionSlug/reference/$endpointSlug': typeof VersionSlugReferenceEndpointSlugRoute
  '/api/ai/chat': typeof ApiAiChatRoute
  '/api/ai/public-chat': typeof ApiAiPublicChatRoute
  '/api/ai/settings': typeof ApiAiSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/$organizationSlug/projects': typeof AppOrganizationSlugProjectsRouteWithChildren
  '/app/$organizationSlug/settings': typeof AppOrganizationSlugSettingsRoute
  '/v/$versionSlug/llms.txt': typeof VVersionSlugLlmsDottxtRoute
  '/v/$versionSlug/openapi.json': typeof VVersionSlugOpenapiDotjsonRoute
  '/docs/$organizationSlug/$projectSlug/$endpointSlug': typeof DocsOrganizationSlugProjectSlugEndpointSlugRoute
  '/docs/$organizationSlug/$projectSlug/llms.txt': typeof DocsOrganizationSlugProjectSlugLlmsDottxtRoute
  '/docs/$organizationSlug/$projectSlug/openapi.json': typeof DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute
  '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md': typeof DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute
  '/v/$versionSlug/guides/$guideSlug': typeof VVersionSlugGuidesGuideSlugRoute
  '/v/$versionSlug/reference/$endpointSlug': typeof VVersionSlugReferenceEndpointSlugRoute
  '/docs/$organizationSlug/$projectSlug/': typeof DocsOrganizationSlugProjectSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/ai': typeof AppOrganizationSlugProjectsProjectSlugAiRoute
  '/app/$organizationSlug/projects/$projectSlug/metrics': typeof AppOrganizationSlugProjectsProjectSlugMetricsRoute
  '/app/$organizationSlug/projects/$projectSlug/settings': typeof AppOrganizationSlugProjectsProjectSlugSettingsRoute
  '/docs/$organizationSlug/$projectSlug/guides/$guideSlug': typeof DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute
  '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md': typeof DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute
  '/app/$organizationSlug/projects/$projectSlug/': typeof AppOrganizationSlugProjectsProjectSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug': typeof AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug': typeof AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/guides/': typeof AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute
  '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/': typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/llms.txt'
    | '/onboarding'
    | '/openapi.json'
    | '/api/execute'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/terms'
    | '/docs/$guideSlug'
    | '/guides/$guideSlug'
    | '/guides/{$guideSlug}.md'
    | '/reference/$endpointSlug'
    | '/reference/{$endpointSlug}.md'
    | '/docs/'
    | '/guides/'
    | '/reference/'
    | '/$versionSlug/docs/$guideSlug'
    | '/$versionSlug/reference/$endpointSlug'
    | '/api/ai/chat'
    | '/api/ai/public-chat'
    | '/api/ai/settings'
    | '/api/auth/$'
    | '/app/$organizationSlug/projects'
    | '/app/$organizationSlug/settings'
    | '/v/$versionSlug/llms.txt'
    | '/v/$versionSlug/openapi.json'
    | '/docs/$organizationSlug/$projectSlug/$endpointSlug'
    | '/docs/$organizationSlug/$projectSlug/llms.txt'
    | '/docs/$organizationSlug/$projectSlug/openapi.json'
    | '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md'
    | '/v/$versionSlug/guides/$guideSlug'
    | '/v/$versionSlug/reference/$endpointSlug'
    | '/docs/$organizationSlug/$projectSlug/'
    | '/app/$organizationSlug/projects/$projectSlug/ai'
    | '/app/$organizationSlug/projects/$projectSlug/metrics'
    | '/app/$organizationSlug/projects/$projectSlug/settings'
    | '/docs/$organizationSlug/$projectSlug/guides/$guideSlug'
    | '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md'
    | '/app/$organizationSlug/projects/$projectSlug/'
    | '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug'
    | '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug'
    | '/app/$organizationSlug/projects/$projectSlug/guides/'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/llms.txt'
    | '/onboarding'
    | '/openapi.json'
    | '/api/execute'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/terms'
    | '/docs/$guideSlug'
    | '/guides/$guideSlug'
    | '/guides/{$guideSlug}.md'
    | '/reference/$endpointSlug'
    | '/reference/{$endpointSlug}.md'
    | '/docs'
    | '/guides'
    | '/reference'
    | '/$versionSlug/docs/$guideSlug'
    | '/$versionSlug/reference/$endpointSlug'
    | '/api/ai/chat'
    | '/api/ai/public-chat'
    | '/api/ai/settings'
    | '/api/auth/$'
    | '/app/$organizationSlug/projects'
    | '/app/$organizationSlug/settings'
    | '/v/$versionSlug/llms.txt'
    | '/v/$versionSlug/openapi.json'
    | '/docs/$organizationSlug/$projectSlug/$endpointSlug'
    | '/docs/$organizationSlug/$projectSlug/llms.txt'
    | '/docs/$organizationSlug/$projectSlug/openapi.json'
    | '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md'
    | '/v/$versionSlug/guides/$guideSlug'
    | '/v/$versionSlug/reference/$endpointSlug'
    | '/docs/$organizationSlug/$projectSlug'
    | '/app/$organizationSlug/projects/$projectSlug/ai'
    | '/app/$organizationSlug/projects/$projectSlug/metrics'
    | '/app/$organizationSlug/projects/$projectSlug/settings'
    | '/docs/$organizationSlug/$projectSlug/guides/$guideSlug'
    | '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md'
    | '/app/$organizationSlug/projects/$projectSlug'
    | '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug'
    | '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug'
    | '/app/$organizationSlug/projects/$projectSlug/guides'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides'
  id:
    | '__root__'
    | '/'
    | '/llms.txt'
    | '/onboarding'
    | '/openapi.json'
    | '/api/execute'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/terms'
    | '/docs/$guideSlug'
    | '/guides/$guideSlug'
    | '/guides/{$guideSlug}.md'
    | '/reference/$endpointSlug'
    | '/reference/{$endpointSlug}.md'
    | '/docs/'
    | '/guides/'
    | '/reference/'
    | '/$versionSlug/docs/$guideSlug'
    | '/$versionSlug/reference/$endpointSlug'
    | '/api/ai/chat'
    | '/api/ai/public-chat'
    | '/api/ai/settings'
    | '/api/auth/$'
    | '/app/$organizationSlug/projects'
    | '/app/$organizationSlug/settings'
    | '/v/$versionSlug/llms.txt'
    | '/v/$versionSlug/openapi.json'
    | '/docs/$organizationSlug/$projectSlug/$endpointSlug'
    | '/docs/$organizationSlug/$projectSlug/llms.txt'
    | '/docs/$organizationSlug/$projectSlug/openapi.json'
    | '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md'
    | '/v/$versionSlug/guides/$guideSlug'
    | '/v/$versionSlug/reference/$endpointSlug'
    | '/docs/$organizationSlug/$projectSlug/'
    | '/app/$organizationSlug/projects/$projectSlug/ai'
    | '/app/$organizationSlug/projects/$projectSlug/metrics'
    | '/app/$organizationSlug/projects/$projectSlug/settings'
    | '/docs/$organizationSlug/$projectSlug/guides/$guideSlug'
    | '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md'
    | '/app/$organizationSlug/projects/$projectSlug/'
    | '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug'
    | '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug'
    | '/app/$organizationSlug/projects/$projectSlug/guides/'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug'
    | '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OnboardingRoute: typeof OnboardingRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  ApiExecuteRoute: typeof ApiExecuteRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthTermsRoute: typeof AuthTermsRoute
  DocsGuideSlugRoute: typeof DocsGuideSlugRoute
  GuidesGuideSlugRoute: typeof GuidesGuideSlugRoute
  GuidesChar123guideSlugChar125DotmdRoute: typeof GuidesChar123guideSlugChar125DotmdRoute
  ReferenceEndpointSlugRoute: typeof ReferenceEndpointSlugRoute
  ReferenceChar123endpointSlugChar125DotmdRoute: typeof ReferenceChar123endpointSlugChar125DotmdRoute
  DocsIndexRoute: typeof DocsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  ReferenceIndexRoute: typeof ReferenceIndexRoute
  VersionSlugDocsGuideSlugRoute: typeof VersionSlugDocsGuideSlugRoute
  VersionSlugReferenceEndpointSlugRoute: typeof VersionSlugReferenceEndpointSlugRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiAiPublicChatRoute: typeof ApiAiPublicChatRoute
  ApiAiSettingsRoute: typeof ApiAiSettingsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AppOrganizationSlugProjectsRoute: typeof AppOrganizationSlugProjectsRouteWithChildren
  AppOrganizationSlugSettingsRoute: typeof AppOrganizationSlugSettingsRoute
  VVersionSlugLlmsDottxtRoute: typeof VVersionSlugLlmsDottxtRoute
  VVersionSlugOpenapiDotjsonRoute: typeof VVersionSlugOpenapiDotjsonRoute
  DocsOrganizationSlugProjectSlugEndpointSlugRoute: typeof DocsOrganizationSlugProjectSlugEndpointSlugRoute
  DocsOrganizationSlugProjectSlugLlmsDottxtRoute: typeof DocsOrganizationSlugProjectSlugLlmsDottxtRoute
  DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute: typeof DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute
  DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute: typeof DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute
  VVersionSlugGuidesGuideSlugRoute: typeof VVersionSlugGuidesGuideSlugRoute
  VVersionSlugReferenceEndpointSlugRoute: typeof VVersionSlugReferenceEndpointSlugRoute
  DocsOrganizationSlugProjectSlugIndexRoute: typeof DocsOrganizationSlugProjectSlugIndexRoute
  DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute: typeof DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute
  DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute: typeof DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/': {
      id: '/reference/'
      path: '/reference'
      fullPath: '/reference/'
      preLoaderRoute: typeof ReferenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/{$endpointSlug}.md': {
      id: '/reference/{$endpointSlug}.md'
      path: '/reference/{$endpointSlug}.md'
      fullPath: '/reference/{$endpointSlug}.md'
      preLoaderRoute: typeof ReferenceChar123endpointSlugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference/$endpointSlug': {
      id: '/reference/$endpointSlug'
      path: '/reference/$endpointSlug'
      fullPath: '/reference/$endpointSlug'
      preLoaderRoute: typeof ReferenceEndpointSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/{$guideSlug}.md': {
      id: '/guides/{$guideSlug}.md'
      path: '/guides/{$guideSlug}.md'
      fullPath: '/guides/{$guideSlug}.md'
      preLoaderRoute: typeof GuidesChar123guideSlugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideSlug': {
      id: '/guides/$guideSlug'
      path: '/guides/$guideSlug'
      fullPath: '/guides/$guideSlug'
      preLoaderRoute: typeof GuidesGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$guideSlug': {
      id: '/docs/$guideSlug'
      path: '/docs/$guideSlug'
      fullPath: '/docs/$guideSlug'
      preLoaderRoute: typeof DocsGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/terms': {
      id: '/auth/terms'
      path: '/auth/terms'
      fullPath: '/auth/terms'
      preLoaderRoute: typeof AuthTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/execute': {
      id: '/api/execute'
      path: '/api/execute'
      fullPath: '/api/execute'
      preLoaderRoute: typeof ApiExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$versionSlug/openapi.json': {
      id: '/v/$versionSlug/openapi.json'
      path: '/v/$versionSlug/openapi.json'
      fullPath: '/v/$versionSlug/openapi.json'
      preLoaderRoute: typeof VVersionSlugOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$versionSlug/llms.txt': {
      id: '/v/$versionSlug/llms.txt'
      path: '/v/$versionSlug/llms.txt'
      fullPath: '/v/$versionSlug/llms.txt'
      preLoaderRoute: typeof VVersionSlugLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$organizationSlug/settings': {
      id: '/app/$organizationSlug/settings'
      path: '/app/$organizationSlug/settings'
      fullPath: '/app/$organizationSlug/settings'
      preLoaderRoute: typeof AppOrganizationSlugSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$organizationSlug/projects': {
      id: '/app/$organizationSlug/projects'
      path: '/app/$organizationSlug/projects'
      fullPath: '/app/$organizationSlug/projects'
      preLoaderRoute: typeof AppOrganizationSlugProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/settings': {
      id: '/api/ai/settings'
      path: '/api/ai/settings'
      fullPath: '/api/ai/settings'
      preLoaderRoute: typeof ApiAiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/public-chat': {
      id: '/api/ai/public-chat'
      path: '/api/ai/public-chat'
      fullPath: '/api/ai/public-chat'
      preLoaderRoute: typeof ApiAiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/chat': {
      id: '/api/ai/chat'
      path: '/api/ai/chat'
      fullPath: '/api/ai/chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$versionSlug/reference/$endpointSlug': {
      id: '/$versionSlug/reference/$endpointSlug'
      path: '/$versionSlug/reference/$endpointSlug'
      fullPath: '/$versionSlug/reference/$endpointSlug'
      preLoaderRoute: typeof VersionSlugReferenceEndpointSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$versionSlug/docs/$guideSlug': {
      id: '/$versionSlug/docs/$guideSlug'
      path: '/$versionSlug/docs/$guideSlug'
      fullPath: '/$versionSlug/docs/$guideSlug'
      preLoaderRoute: typeof VersionSlugDocsGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$organizationSlug/$projectSlug/': {
      id: '/docs/$organizationSlug/$projectSlug/'
      path: '/docs/$organizationSlug/$projectSlug'
      fullPath: '/docs/$organizationSlug/$projectSlug/'
      preLoaderRoute: typeof DocsOrganizationSlugProjectSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$versionSlug/reference/$endpointSlug': {
      id: '/v/$versionSlug/reference/$endpointSlug'
      path: '/v/$versionSlug/reference/$endpointSlug'
      fullPath: '/v/$versionSlug/reference/$endpointSlug'
      preLoaderRoute: typeof VVersionSlugReferenceEndpointSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$versionSlug/guides/$guideSlug': {
      id: '/v/$versionSlug/guides/$guideSlug'
      path: '/v/$versionSlug/guides/$guideSlug'
      fullPath: '/v/$versionSlug/guides/$guideSlug'
      preLoaderRoute: typeof VVersionSlugGuidesGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md': {
      id: '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md'
      path: '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md'
      fullPath: '/docs/$organizationSlug/$projectSlug/{$endpointSlug}.md'
      preLoaderRoute: typeof DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$organizationSlug/$projectSlug/openapi.json': {
      id: '/docs/$organizationSlug/$projectSlug/openapi.json'
      path: '/docs/$organizationSlug/$projectSlug/openapi.json'
      fullPath: '/docs/$organizationSlug/$projectSlug/openapi.json'
      preLoaderRoute: typeof DocsOrganizationSlugProjectSlugOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$organizationSlug/$projectSlug/llms.txt': {
      id: '/docs/$organizationSlug/$projectSlug/llms.txt'
      path: '/docs/$organizationSlug/$projectSlug/llms.txt'
      fullPath: '/docs/$organizationSlug/$projectSlug/llms.txt'
      preLoaderRoute: typeof DocsOrganizationSlugProjectSlugLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$organizationSlug/$projectSlug/$endpointSlug': {
      id: '/docs/$organizationSlug/$projectSlug/$endpointSlug'
      path: '/docs/$organizationSlug/$projectSlug/$endpointSlug'
      fullPath: '/docs/$organizationSlug/$projectSlug/$endpointSlug'
      preLoaderRoute: typeof DocsOrganizationSlugProjectSlugEndpointSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$organizationSlug/projects/$projectSlug/': {
      id: '/app/$organizationSlug/projects/$projectSlug/'
      path: '/$projectSlug'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugIndexRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md': {
      id: '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md'
      path: '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md'
      fullPath: '/docs/$organizationSlug/$projectSlug/guides/{$guideSlug}.md'
      preLoaderRoute: typeof DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$organizationSlug/$projectSlug/guides/$guideSlug': {
      id: '/docs/$organizationSlug/$projectSlug/guides/$guideSlug'
      path: '/docs/$organizationSlug/$projectSlug/guides/$guideSlug'
      fullPath: '/docs/$organizationSlug/$projectSlug/guides/$guideSlug'
      preLoaderRoute: typeof DocsOrganizationSlugProjectSlugGuidesGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$organizationSlug/projects/$projectSlug/settings': {
      id: '/app/$organizationSlug/projects/$projectSlug/settings'
      path: '/$projectSlug/settings'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/settings'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugSettingsRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/metrics': {
      id: '/app/$organizationSlug/projects/$projectSlug/metrics'
      path: '/$projectSlug/metrics'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/metrics'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugMetricsRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/ai': {
      id: '/app/$organizationSlug/projects/$projectSlug/ai'
      path: '/$projectSlug/ai'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/ai'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugAiRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/guides/': {
      id: '/app/$organizationSlug/projects/$projectSlug/guides/'
      path: '/$projectSlug/guides'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/guides/'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugGuidesIndexRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug': {
      id: '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug'
      path: '/$projectSlug/reference/$endpointSlug'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/reference/$endpointSlug'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug': {
      id: '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug'
      path: '/$projectSlug/guides/$guideSlug'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/guides/$guideSlug'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/': {
      id: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/'
      path: '/$projectSlug/versions/$versionSlug'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings': {
      id: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings'
      path: '/$projectSlug/versions/$versionSlug/settings'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/settings'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation': {
      id: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation'
      path: '/$projectSlug/versions/$versionSlug/navigation'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/navigation'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/': {
      id: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/'
      path: '/$projectSlug/versions/$versionSlug/guides'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug': {
      id: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug'
      path: '/$projectSlug/versions/$versionSlug/reference/$endpointSlug'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/reference/$endpointSlug'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
    '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug': {
      id: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug'
      path: '/$projectSlug/versions/$versionSlug/guides/$guideSlug'
      fullPath: '/app/$organizationSlug/projects/$projectSlug/versions/$versionSlug/guides/$guideSlug'
      preLoaderRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRouteImport
      parentRoute: typeof AppOrganizationSlugProjectsRoute
    }
  }
}

interface AppOrganizationSlugProjectsRouteChildren {
  AppOrganizationSlugProjectsProjectSlugAiRoute: typeof AppOrganizationSlugProjectsProjectSlugAiRoute
  AppOrganizationSlugProjectsProjectSlugMetricsRoute: typeof AppOrganizationSlugProjectsProjectSlugMetricsRoute
  AppOrganizationSlugProjectsProjectSlugSettingsRoute: typeof AppOrganizationSlugProjectsProjectSlugSettingsRoute
  AppOrganizationSlugProjectsProjectSlugIndexRoute: typeof AppOrganizationSlugProjectsProjectSlugIndexRoute
  AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute: typeof AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute
  AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute: typeof AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute
  AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute: typeof AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute
  AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute: typeof AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute
}

const AppOrganizationSlugProjectsRouteChildren: AppOrganizationSlugProjectsRouteChildren =
  {
    AppOrganizationSlugProjectsProjectSlugAiRoute:
      AppOrganizationSlugProjectsProjectSlugAiRoute,
    AppOrganizationSlugProjectsProjectSlugMetricsRoute:
      AppOrganizationSlugProjectsProjectSlugMetricsRoute,
    AppOrganizationSlugProjectsProjectSlugSettingsRoute:
      AppOrganizationSlugProjectsProjectSlugSettingsRoute,
    AppOrganizationSlugProjectsProjectSlugIndexRoute:
      AppOrganizationSlugProjectsProjectSlugIndexRoute,
    AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute:
      AppOrganizationSlugProjectsProjectSlugGuidesGuideSlugRoute,
    AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute:
      AppOrganizationSlugProjectsProjectSlugReferenceEndpointSlugRoute,
    AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute:
      AppOrganizationSlugProjectsProjectSlugGuidesIndexRoute,
    AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute:
      AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugNavigationRoute,
    AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute:
      AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugSettingsRoute,
    AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute:
      AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugIndexRoute,
    AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute:
      AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesGuideSlugRoute,
    AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute:
      AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugReferenceEndpointSlugRoute,
    AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute:
      AppOrganizationSlugProjectsProjectSlugVersionsVersionSlugGuidesIndexRoute,
  }

const AppOrganizationSlugProjectsRouteWithChildren =
  AppOrganizationSlugProjectsRoute._addFileChildren(
    AppOrganizationSlugProjectsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OnboardingRoute: OnboardingRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  ApiExecuteRoute: ApiExecuteRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthTermsRoute: AuthTermsRoute,
  DocsGuideSlugRoute: DocsGuideSlugRoute,
  GuidesGuideSlugRoute: GuidesGuideSlugRoute,
  GuidesChar123guideSlugChar125DotmdRoute:
    GuidesChar123guideSlugChar125DotmdRoute,
  ReferenceEndpointSlugRoute: ReferenceEndpointSlugRoute,
  ReferenceChar123endpointSlugChar125DotmdRoute:
    ReferenceChar123endpointSlugChar125DotmdRoute,
  DocsIndexRoute: DocsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  ReferenceIndexRoute: ReferenceIndexRoute,
  VersionSlugDocsGuideSlugRoute: VersionSlugDocsGuideSlugRoute,
  VersionSlugReferenceEndpointSlugRoute: VersionSlugReferenceEndpointSlugRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiAiPublicChatRoute: ApiAiPublicChatRoute,
  ApiAiSettingsRoute: ApiAiSettingsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AppOrganizationSlugProjectsRoute:
    AppOrganizationSlugProjectsRouteWithChildren,
  AppOrganizationSlugSettingsRoute: AppOrganizationSlugSettingsRoute,
  VVersionSlugLlmsDottxtRoute: VVersionSlugLlmsDottxtRoute,
  VVersionSlugOpenapiDotjsonRoute: VVersionSlugOpenapiDotjsonRoute,
  DocsOrganizationSlugProjectSlugEndpointSlugRoute:
    DocsOrganizationSlugProjectSlugEndpointSlugRoute,
  DocsOrganizationSlugProjectSlugLlmsDottxtRoute:
    DocsOrganizationSlugProjectSlugLlmsDottxtRoute,
  DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute:
    DocsOrganizationSlugProjectSlugOpenapiDotjsonRoute,
  DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute:
    DocsOrganizationSlugProjectSlugChar123endpointSlugChar125DotmdRoute,
  VVersionSlugGuidesGuideSlugRoute: VVersionSlugGuidesGuideSlugRoute,
  VVersionSlugReferenceEndpointSlugRoute:
    VVersionSlugReferenceEndpointSlugRoute,
  DocsOrganizationSlugProjectSlugIndexRoute:
    DocsOrganizationSlugProjectSlugIndexRoute,
  DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute:
    DocsOrganizationSlugProjectSlugGuidesGuideSlugRoute,
  DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute:
    DocsOrganizationSlugProjectSlugGuidesChar123guideSlugChar125DotmdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
